# Generated by Django 4.1.2 on 2022-11-18 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('T', 'Teacher'), ('A', 'Admin'), ('M', 'Maintanance')], default='T', max_length=1, null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='a@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', null=True, upload_to='student_img'),
        ),
        migrations.AddField(
            model_name='student',
            name='std',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(default='default.jpg', null=True, upload_to='student_img')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1, null=True)),
                ('DOB', models.DateField(null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.IntegerField(default=2022, null=True)),
                ('email_id', models.EmailField(default='@gmail.com', max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('logo', models.ImageField(default='default.jpg', upload_to='school_logos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
